[package]
name = "web_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.10.10", features = ["blocking"] }
eyre = "0.6"
select = "0.6.0"
url = "2.5.4"
log = "0.4.22"
env_logger = "0.11.5"
thiserror = "2.0.3"
